include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    depend_on_referenced_packages: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
